version: '3.8'

services:
  flaskapp:
    build: .
    container_name: flaskapp
    ports:
      - "8000:8000"
    restart: always
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8000
      - PYTHONUNBUFFERED=1
